use UNIVER 
select PULPIT.PULPIT_NAME, PROFESSION.PROFESSION_NAME
from PULPIT,FACULTY,PROFESSION
where PULPIT.FACULTY =FACULTY.FACULTY and FACULTY.FACULTY =PROFESSION.FACULTY
and PROFESSION IN(select PROFESSION_NAME from PROFESSION where (PROFESSION_NAME like '%технологи%'))